stages:
  - test
  - build
  - deploy

test:
  stage: test
  script:
    - echo "Testing"
    - echo "Test Complete"

gradle-build:
  stage: build
  before_script:
    - echo "Start building gradle"
  script:
    - ./gradlew build
  artifacts:
    paths:
      - build/libs/*.jar
deploy:
  script:
    - docker-compose up -d --build
