stages:
  - build
  - deploy
services:
  - docker:dind


gradle-build:
  image: openjdk:11
  stage: build
  before_script:
    - echo "Start building gradle"
  script:
    - chmod +x gradlew
    - ./gradlew build
  artifacts:
    paths:
      - build/libs/*.jar
deploy:
  stage: deploy
  script:
    - docker-compose up -d --build
