image: docker
stages:
  - build
  - deploy

services:
  - docker:dind

cache:
  key: gradle-cache-key
  paths:
    - .gradle/wrapper
    - .gradle/caches
  policy: pull

gradle-build:
  stage: build
  image: openjdk:11
  before_script:
    - echo "Start building gradle"
  script:
    - chmod +x gradlew
    - ./gradlew build
  only:
    changes:
      - "*.gradle"
      - gradle.properties
  cache:
    key: gradle-cache-key
    paths:
      - .gradle/wrapper
      - .gradle/caches
    policy: push
  artifacts:
    paths:
      - build/libs/*.jar

deploy:
  stage: deploy
  script:
    - docker-compose --version
    - docker-compose up --build
