image: docker
stages:
  - build
  - deploy

before_script:
    - export GRADLE_USER_HOME=`pwd`/.gradle

cache:
  paths:
     - .gradle/wrapper
     - .gradle/caches

services:
  - docker:dind

build:
  stage: build
  script:
    - chmod +400 ./gradlew
    - ./gradlew build
  artifacts:
    paths:
      - build/libs/*.jar

deploy:
  stage: deploy
  script:
    - docker-compose --version
    - docker-compose up --build
