##########################
# SERVER
##########################
server:
  port: ${SERVER_PORT:8080}
  host: ${SERVER_HOST:http://localhost:8080}

##########################
# KEYCLOAK
##########################
keycloak:
  auth-server-url: ${KEYCLOAK_SERVER_URL:}
  credentials:
    secret: ${KEYCLOAK_CLIENT_SECRET:}
  resource: ${KEYCLOAK_CLIENT_ID:}
  realm: ${KEYCLOAK_REALM:}
  use-resource-role-mappings: true
keycloak-client:
  username: ${KEYCLOAK_CLIENT_USERNAME:}
  password: ${KEYCLOAK_CLIENT_PASSWORD:}

##########################
# REDIS
##########################
redis:
  host: ${REDIS_HOST:http://localhost}
  port: ${REDIS_PORT:6379}
  password: ${REDIS_PASSWORD:}

##########################
# DATASOURCE
##########################
spring:
  datasource:
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5432/bike}
    username: ${DATASOURCE_USERNAME:postgres}
    password: ${DATASOURCE_PASSWORD:}
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

##########################
# GOOGLE CLIENT
##########################
google:
  client-id: ${GOOGLE_CLIENT_ID:}
  client-secret: ${GOOGLE_CLIENT_SECRET:}
  redirect-uri: ${GOOGLE_REDIRECT_URI:}
  auth-server-url: ${GOOGLE_AUTH_URL:}
  valid-domain: ${GOOGLE_VALID_DOMAIN:fpt.edu.vn}


