##########################
# SERVER
##########################
server:
  port: ${SERVER_PORT:8080}
  host: ${SERVER_HOST:http://localhost:8080}

##########################
# KEYCLOAK
##########################
keycloak:
  realm: ${KEYCLOAK_REALM:}
  auth-server-url: ${KEYCLOAK_SERVER_URL:}
  ssl-required: ${KEYCLOAK_SSL_REQUIRED:external}
  credentials:
    secret: ${KEYCLOAK_CLIENT_SECRET:}
  resource: ${KEYCLOAK_CLIENT_ID:}
  bearer-only: true
  use-resource-role-mappings: true
  allow-any-hostname: true

keycloak-client:
  username: ${KEYCLOAK_CLIENT_USERNAME:}
  password: ${KEYCLOAK_CLIENT_PASSWORD:}

##########################
# REDIS
##########################
redis:
  host: ${REDIS_HOST:http://localhost}
  port: ${REDIS_PORT:6379}
  password: ${REDIS_PASSWORD:}

##########################
# DATASOURCE
##########################
spring:
  datasource:
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5432/bike}
    username: ${DATASOURCE_USERNAME:postgres}
    password: ${DATASOURCE_PASSWORD:013845}
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
        format_sql: true
    hibernate:
      ddl-auto: update

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB


##########################
# GOOGLE CLIENT
##########################
google:
  client-id: ${GOOGLE_CLIENT_ID:}
  client-secret: ${GOOGLE_CLIENT_SECRET:}
  auth-server-url: ${GOOGLE_AUTH_URL:}
  valid-domain: ${GOOGLE_VALID_DOMAIN:fpt.edu.vn}


post-threshold: ${POST_THRESHOLD_IN_MINUTES:30}
trip_cancel_threshold: ${TRIP_CANCEL_THRESHOLD_IN_MINUTES:30}


##########################
# AWS
##########################
aws:
  bucket: ${AWS_BUCKET_NAME:swd-bike}
  region: ${AWS_BUCKET_REGION:ap-southeast-1}
  access-key: ${AWS_ACCESS_KEY:AKIAUDA34SKADERFJ3ST}
  secret-key: ${AWS_SECRET_KEY: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}