##########################
# SERVER
##########################
server:
  port: ${SERVER_PORT:1125}
  host: ${SERVER_HOST:http://localhost:1125}

##########################
# KEYCLOAK
##########################
keycloak:
  auth-server-url: ${KEYCLOAK_SERVER_URL:https://52.74.214.224:8180/}
  credentials:
    secret: ${KEYCLOAK_CLIENT_SECRET:wDI5spnVvFkQIwwUg9jNbrZza4fU22aa}
  resource: ${KEYCLOAK_CLIENT_ID:bike-client}
  realm: ${KEYCLOAK_REALM:bike}
keycloak-client:
  username: ${KEYCLOAK_CLIENT_USERNAME:admin}
  password: ${KEYCLOAK_CLIENT_PASSWORD:Aqswde123@}

##########################
# REDIS
##########################
redis:
  host: ${REDIS_HOST:http://localhost}
  port: ${REDIS_PORT:6379}
  password: ${REDIS_PASSWORD:}

##########################
# DATASOURCE
##########################
spring:
  datasource:
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5432/bike}
    username: ${DATASOURCE_USERNAME:postgres}
    password: ${DATASOURCE_PASSWORD:1811}
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

##########################
# GOOGLE CLIENT
##########################
google:
  client-id: ${GOOGLE_CLIENT_ID:112402231809-sju8kah621nj78kgtjsc51aqk25ule4d.apps.googleusercontent.com}
  client-secret: ${GOOGLE_CLIENT_SECRET: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}
  redirect-uri: ${GOOGLE_REDIRECT_URI:https://oidcdebugger.com/debug}
  auth-server-url: ${GOOGLE_AUTH_URL:https://oauth2.googleapis.com/token}
  valid-domain: ${GOOGLE_VALID_DOMAIN:fpt.edu.vn}


